"use client";

import { useEffect, useMemo, useReducer, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { DesktopIcons } from "@/components/desktop/desktop-icons";
import { DesktopTaskbar } from "@/components/desktop/desktop-taskbar";
import { DesktopTopbar } from "@/components/desktop/desktop-topbar";
import { DesktopWindowManager } from "@/components/desktop/desktop-window-manager";
import { CommandPalette } from "@/components/layout/command-palette";
import { MIN_WINDOW_SIZES } from "@/lib/desktop/constants";
import { DESKTOP_OPEN_APP_EVENT } from "@/lib/desktop/events";
import { buildDashboardQueryFromState, parseDesktopDeepLinkFromSearchParams } from "@/lib/desktop/query";
import { createInitialDesktopState, desktopReducer } from "@/lib/desktop/reducer";
import type { DesktopAppId, DesktopDeepLink, DesktopWindowRect } from "@/lib/desktop/types";

export function DesktopShell() {
  const searchParams = useSearchParams();
  const [state, dispatch] = useReducer(desktopReducer, undefined, createInitialDesktopState);
  const [deepLinkWarning, setDeepLinkWarning] = useState<string | null>(null);

  const workspaceRef = useRef<HTMLDivElement | null>(null);
  const [workspaceSize, setWorkspaceSize] = useState<Pick<DesktopWindowRect, "width" | "height">>({
    width: 1440,
    height: 900,
  });

  const searchKey = searchParams.toString();
  const lastAppliedSearchKeyRef = useRef<string>("");
  const activeQuery = useMemo(() => buildDashboardQueryFromState(state), [state]);

  useEffect(() => {
    if (!workspaceRef.current) return;

    const updateSize = () => {
      if (!workspaceRef.current) return;
      const rect = workspaceRef.current.getBoundingClientRect();
      setWorkspaceSize({ width: Math.floor(rect.width), height: Math.floor(rect.height) });
    };

    updateSize();

    const observer = new ResizeObserver(updateSize);
    observer.observe(workspaceRef.current);
    window.addEventListener("resize", updateSize);

    return () => {
      observer.disconnect();
      window.removeEventListener("resize", updateSize);
    };
  }, []);

  useEffect(() => {
    if (searchKey === lastAppliedSearchKeyRef.current) return;

    // Ignore query updates that already match current in-memory desktop state.
    // These are usually generated by our own URL sync and should not re-open apps.
    if (searchKey === activeQuery) {
      lastAppliedSearchKeyRef.current = searchKey;
      setDeepLinkWarning(null);
      return;
    }

    const params = new URLSearchParams(searchKey);
    const deepLink = parseDesktopDeepLinkFromSearchParams(params);
    if (!deepLink) {
      if (params.get("app")) {
        setDeepLinkWarning("Unknown app deep-link. Opened default dashboard view.");
      }
      return;
    }

    dispatch({
      type: "OPEN_DEEP_LINK",
      appId: deepLink.appId,
      viewState: deepLink.viewState,
    });
    setDeepLinkWarning(null);

    lastAppliedSearchKeyRef.current = searchKey;
  }, [activeQuery, searchKey]);

  useEffect(() => {
    const handler = (event: Event) => {
      const custom = event as CustomEvent<DesktopDeepLink>;
      if (!custom.detail?.appId) return;
      dispatch({
        type: "OPEN_DEEP_LINK",
        appId: custom.detail.appId,
        viewState: custom.detail.viewState,
      });
    };

    window.addEventListener(DESKTOP_OPEN_APP_EVENT, handler as EventListener);
    return () => {
      window.removeEventListener(DESKTOP_OPEN_APP_EVENT, handler as EventListener);
    };
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Enter" || !state.selectedIconId) return;
      dispatch({ type: "OPEN_APP", appId: state.selectedIconId });
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [state.selectedIconId]);

  useEffect(() => {
    // Ignore transient tiny measurements during route/search transitions.
    // These can otherwise clamp windows down to minimum size unexpectedly.
    if (workspaceSize.width < 640 || workspaceSize.height < 420) {
      return;
    }

    const inset = 8;
    for (const [appId, windowState] of Object.entries(state.windows) as Array<
      [DesktopAppId, (typeof state.windows)[DesktopAppId]]
    >) {
      if (!windowState.isOpen || windowState.isMaximized) continue;

      const min = MIN_WINDOW_SIZES[appId];
      const maxWidth = Math.max(min.width, workspaceSize.width - inset * 2);
      const maxHeight = Math.max(min.height, workspaceSize.height - inset * 2);
      const width = Math.min(windowState.rect.width, maxWidth);
      const height = Math.min(windowState.rect.height, maxHeight);
      const maxX = Math.max(inset, workspaceSize.width - width - inset);
      const maxY = Math.max(inset, workspaceSize.height - height - inset);
      const x = Math.min(Math.max(windowState.rect.x, inset), maxX);
      const y = Math.min(Math.max(windowState.rect.y, inset), maxY);

      if (
        x !== windowState.rect.x ||
        y !== windowState.rect.y ||
        width !== windowState.rect.width ||
        height !== windowState.rect.height
      ) {
        dispatch({
          type: "MOVE_RESIZE_APP",
          appId,
          rect: { x, y, width, height },
        });
      }
    }
  }, [workspaceSize, state.windows]);

  function openApp(appId: DesktopAppId) {
    dispatch({ type: "OPEN_APP", appId });
  }

  function handleTaskClick(appId: DesktopAppId) {
    const target = state.windows[appId];

    if (!target.isOpen) {
      dispatch({ type: "OPEN_APP", appId });
      return;
    }

    if (target.isMinimized) {
      dispatch({ type: "FOCUS_APP", appId });
      return;
    }

    if (state.activeAppId === appId) {
      dispatch({ type: "MINIMIZE_APP", appId });
      return;
    }

    dispatch({ type: "FOCUS_APP", appId });
  }

  return (
    <div className="flex min-h-screen flex-col bg-[var(--os-paper)] text-[var(--os-ink)]">
      <DesktopTopbar />

      <main
        ref={workspaceRef}
        onClick={() => dispatch({ type: "CLEAR_ICON_SELECTION" })}
        className="relative min-h-0 flex-1 overflow-hidden"
        style={{
          backgroundColor: "#fcf3de",
          backgroundImage: "url('/desktop/wallpaper-v2-artwork.png')",
          backgroundSize: "cover",
          backgroundPosition: "center center",
          backgroundRepeat: "no-repeat",
        }}
      >
        <div className="pointer-events-none absolute inset-0 opacity-[0.12] [background-image:radial-gradient(circle_at_2px_2px,rgba(26,22,17,0.22)_1px,transparent_0)] [background-size:8px_8px]" />

        <DesktopIcons
          selectedIconId={state.selectedIconId}
          iconPositions={state.iconPositions}
          workspaceSize={workspaceSize}
          onSelectIcon={(appId) => dispatch({ type: "SELECT_ICON", appId })}
          onOpenApp={openApp}
          onMoveIcon={(appId, position) => dispatch({ type: "MOVE_ICON", appId, position })}
        />

        <DesktopWindowManager
          windows={state.windows}
          activeAppId={state.activeAppId}
          onFocus={(appId) => dispatch({ type: "FOCUS_APP", appId })}
          onClose={(appId) => dispatch({ type: "CLOSE_APP", appId })}
          onMinimize={(appId) => dispatch({ type: "MINIMIZE_APP", appId })}
          onToggleMaximize={(appId) =>
            dispatch({
              type: "TOGGLE_MAXIMIZE_APP",
              appId,
              viewport: workspaceSize,
            })
          }
          onMoveResize={(appId, rect) => dispatch({ type: "MOVE_RESIZE_APP", appId, rect })}
        />

        {deepLinkWarning && (
          <div className="absolute right-4 top-4 z-50 rounded-[8px] border border-[var(--os-line)] bg-[var(--os-panel)] px-3 py-2 text-xs text-[var(--os-ink-soft)] shadow-sm">
            {deepLinkWarning}
          </div>
        )}
      </main>

      <DesktopTaskbar
        windows={state.windows}
        activeAppId={state.activeAppId}
        onTaskClick={handleTaskClick}
      />

      <CommandPalette />
    </div>
  );
}
